### ISSUE TITLE
truffle serve giving error

### ISSUE THREAD

**Issue by akumthek** [dob/auctionhouse#43]
Created a git repository and tried to run the app following instructions.
I am using ubuntu 16 on oracle virtual box on windows 8.1 professional
node version is 8.11.1

I get the error on 'truffle serve'

bc@bc-VirtualBox:~/projects/auctionhouse$ truffle serve
Serving static assets in ./build on port 8080...
Rebuilding...

/usr/local/lib/node_modules/truffle/build/webpack:/~/chokidar/lib/fsevents-handler.js:26
  return (new fsevents(path)).on('fsevent', callback).start();
^
TypeError: fsevents is not a constructor
    at createFSEventsInstance (/usr/local/lib/node_modules/truffle/build/webpack:/~/chokidar/lib/fsevents-handler.js:26:1)
    at setFSEventsListener (/usr/local/lib/node_modules/truffle/build/webpack:/~/chokidar/lib/fsevents-handler.js:80:1)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/usr/local/lib/node_modules/truffle/build/webpack:/~/chokidar/lib/fsevents-handler.js:244:1)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/chokidar/lib/fsevents-handler.js:378:1)
    at LOOP (fs.js:1753:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
bc@bc-VirtualBox:~/projects/auctionhouse$

**Comment by akumthek** [comment]
tried with and without Ganache running in the background

**Comment by wu2816** [comment]
Disable the FsEvents steps:
//Edit the following file
C:\Users\my_window_username\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js
//comment the following line of code.
// if (!FsEventsHandler.canUse()) opts.useFsEvents = false;
//add this line.
opts.useFsEvents = false;

**Comment by SalmanCse** [comment]
truffle unboxwebpack
Downloading...
Error: Something already exists at the destination. `truffle init` and `truffle unbox` must be executed in an empty folder. Stopping to prevent overwriting data.
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-box/lib/utils/unbox.js:22:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
